# Generated by Django 3.2.8 on 2021-10-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(default='mforms/static/images/default.png', upload_to='uploads'),
        ),
    ]
