# Generated by Django 3.2.8 on 2021-10-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mforms', '0002_student_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(default='mforms/static/images/default_img.png', upload_to='uploads'),
        ),
    ]
