# Generated by Django 3.2.8 on 2021-10-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mforms', '0003_alter_student_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='img',
            new_name='image',
        ),
    ]
